(function(g){g.map=function(){var n=function(a,c){switch(c){case 0:var j=a.area.length;if(a.type==g.map.type.ANGLE_90){for(var b=0;b<j;b++){a.area[b].unshift({id:a.maps[a.currentRow+b][a.currentCol-1],x:a.area[b][0].x-a.tileWidth,y:a.area[b][0].y});a.area[b].pop()}a.dx-=a.tileWidth}else if(a.type==g.map.type.STAGGERED){for(b=0;b<j;b++){a.area[b].unshift({id:a.maps[a.currentRow+b][a.currentCol-1],x:a.area[b][0].x-a.tileWidth,y:a.area[b][0].y});a.area[b].pop()}a.dx-=a.tileWidth}else if(a.type==g.map.type.DIAMOND){for(b=
0;b<j;b++){a.area[b].unshift({id:a.maps[a.currentRow+b][a.currentCol-1],x:a.area[b][0].x-a.tileWidth/2,y:a.area[b][0].y+a.tileHeight/2});a.area[b].pop()}a.dx-=a.tileWidth/2;a.dy+=a.tileHeight/2}a.currentCol--;break;case 1:j=a.area.length;if(a.type==g.map.type.ANGLE_90){for(b=0;b<j;b++){a.area[b].push({id:a.maps[a.currentRow+b][a.currentCol+a.area[0].length],x:a.area[b][a.area[b].length-1].x+a.tileWidth,y:a.area[b][0].y});a.area[b].shift()}a.dx+=a.tileWidth}else if(a.type==g.map.type.STAGGERED){for(b=
0;b<j;b++){a.area[b].push({id:a.maps[a.currentRow+b][a.currentCol+a.area[0].length],x:a.area[b][a.area[b].length-1].x+a.tileWidth,y:a.area[b][0].y});a.area[b].shift()}a.dx+=a.tileWidth}else if(a.type==g.map.type.DIAMOND){for(b=0;b<j;b++){a.area[b].push({id:a.maps[a.currentRow+b][a.currentCol+a.area[0].length],x:a.area[b][a.area[b].length-1].x+a.tileWidth/2,y:a.area[b][a.area[b].length-1].y-a.tileHeight/2});a.area[b].shift()}a.dx+=a.tileWidth/2;a.dy-=a.tileHeight/2}a.currentCol++;break;case 2:var m=
[];j=a.area[0].length;if(a.type==g.map.type.ANGLE_90){for(b=0;b<j;b++)m.push({id:a.maps[a.currentRow-1][a.currentCol+b],x:a.area[0][b].x,y:a.area[0][b].y-a.tileHeight});a.dy-=a.tileHeight}else if(a.type==g.map.type.STAGGERED){var t=(a.currentRow-1)%2==0?-parseInt(a.tileWidth/2):parseInt(a.tileWidth/2);for(b=0;b<j;b++)m.push({id:a.maps[a.currentRow-1][a.currentCol+b],x:a.area[0][b].x+t,y:a.area[0][b].y-parseInt(a.tileHeight/2)});a.dy-=parseInt(a.tileHeight/2)}else if(a.type==g.map.type.DIAMOND){for(b=
0;b<j;b++)m.push({id:a.maps[a.currentRow-1][a.currentCol+b],x:a.area[0][b].x-a.tileWidth/2,y:a.area[0][b].y-a.tileHeight/2});a.dx-=a.tileWidth/2;a.dy-=a.tileHeight/2}a.area.unshift(m);a.area.pop();a.currentRow--;break;case 3:m=[];j=a.area[0].length;if(a.type==g.map.type.ANGLE_90){for(b=0;b<j;b++)m.push({id:a.maps[a.currentRow+a.area.length][a.currentCol+b],x:a.area[0][b].x,y:a.area[a.area.length-1][b].y+a.tileHeight});a.dy+=a.tileHeight}else if(a.type==g.map.type.STAGGERED){t=(a.currentRow+a.area.length)%
2==0?-parseInt(a.tileWidth/2):parseInt(a.tileWidth/2);for(b=0;b<j;b++)m.push({id:a.maps[a.currentRow+a.area.length][a.currentCol+b],x:a.area[a.area.length-1][b].x+t,y:a.area[a.area.length-1][b].y+parseInt(a.tileHeight/2)});a.dy+=parseInt(a.tileHeight/2)}else if(a.type==g.map.type.DIAMOND){for(b=0;b<j;b++)m.push({id:a.maps[a.currentRow+a.area.length][a.currentCol+b],x:a.area[a.area.length-1][b].x+a.tileWidth/2,y:a.area[a.area.length-1][b].y+a.tileHeight/2});a.dx+=a.tileWidth/2;a.dy+=a.tileHeight/2}a.area.push(m);
a.area.shift();a.currentRow++}},u=function(a,c){if(a.type==g.map.type.ANGLE_90)if(c>0){c=c>a.tileWidth?a.tileWidth:c;if(a.currentCol==0)if(a.dx==a.tileWidth)return 0;else if(a.dx+c>a.tileWidth)c=a.tileWidth-a.dx;a.dx+=c;a.dx>=a.tileWidth&&a.currentCol>0&&n(a,0)}else{if(c<0){c=c<-a.tileWidth?-a.tileWidth:c;if(a.currentCol+a.showCol==a.maps[0].length)if(a.dx==-a.tileWidth)return 0;else if(a.dx+c<-a.tileWidth)c=-(a.tileWidth+a.dx);a.dx+=c;a.dx<=-a.tileWidth&&a.currentCol+a.area[0].length<a.maps[0].length&&
n(a,1)}}else if(a.type==g.map.type.STAGGERED)if(c>0){c=c>a.tileWidth?a.tileWidth:c;if(a.currentCol==0)if(a.dx==a.tileWidth)return 0;else if(a.dx+c>a.tileWidth)c=a.tileWidth-a.dx;a.dx+=c;a.dx>=a.tileWidth&&a.currentCol>0&&n(a,0)}else if(c<0){c=c<-a.tileWidth?-a.tileWidth:c;if(a.currentCol+a.showCol==a.maps[0].length)if(a.dx==-a.tileWidth*1.5)return 0;else if(a.dx+c<-a.tileWidth*1.5)c=-(a.tileWidth*1.5+a.dx);a.dx+=c;a.dx<=-a.tileWidth&&a.currentCol+a.area[0].length<a.maps[0].length&&n(a,1)}return c},
v=function(a,c){if(a.type==g.map.type.ANGLE_90)if(c>0){c=c>a.tileHeight?a.tileHeight:c;if(a.currentRow==0)if(a.dy==a.tileHeight)return 0;else if(a.dy+c>a.tileHeight)c=a.tileHeight-a.dy;a.dy+=c;a.dy>=a.tileHeight&&a.currentRow>0&&n(a,2)}else{if(c<0){c=c<-a.tileHeight?-a.tileHeight:c;if(a.currentRow+a.showRow==a.maps.length)if(a.dy==-a.tileHeight)return 0;else if(a.dy+c<-a.tileHeight)c=-(a.tileHeight+a.dy);a.dy+=c;a.dy<=-a.tileHeight&&a.currentRow+a.area.length<a.maps.length&&n(a,3)}}else if(a.type==
g.map.type.STAGGERED)if(c>0){c=c>parseInt(a.tileHeight/2)?parseInt(a.tileHeight/2):c;if(a.currentRow==0)if(a.dy==a.tileHeight)return 0;else if(a.dy+c>a.tileHeight)c=a.tileHeight-a.dy;a.dy+=c;a.dy>=parseInt(a.tileHeight/2)&&a.currentRow>0&&n(a,2)}else if(c<0){c=c<-parseInt(a.tileHeight/2)?-parseInt(a.tileHeight/2):c;if(a.currentRow+a.showRow==a.maps.length)if(a.dy==-a.tileHeight*1.5)return 0;else if(a.dy+c<-a.tileHeight*1.5)c=-(a.tileHeight*1.5+a.dy);a.dy+=c;a.dy<=-parseInt(a.tileHeight/2)&&a.currentRow+
a.area.length<a.maps.length&&n(a,3)}return c};return function(a,c,j,b,m,t,w,x,y,z,A,B){this.maps=a||[[]];this.area=[];this.screenWidth=c||240;this.screenHeight=j||320;this.tileWidth=b||40;this.tileHeight=m||40;this.type=t||g.map.type.ANGLE_90;this.currentCol=this.currentRow=0;this.showRow=y||0;this.showCol=z||0;this.x=A||0;this.y=B||0;this.absoluteY=this.absoluteX=this.dy=this.dx=this.mapSpeedY=this.mapSpeedX=0;this.refresh=function(f,d,e,i){var k,p,q,r,o,s;this.area=[];f=f<0?0:f;d=d<0?0:d;if(this.type==
g.map.type.ANGLE_90){var h=Math.round((this.screenHeight+2*this.tileHeight)/this.tileHeight),l=Math.round((this.screenWidth+2*this.tileWidth)/this.tileWidth);k=f+h<=this.maps.length-1?f:this.maps.length-h<0?0:this.maps.length-h;p=f+h-1<=this.maps.length-1?f+h-1:this.maps.length-1;q=d+l<=this.maps[0].length-1?d:this.maps[0].length-l<0?0:this.maps[0].length-l;r=d+l-1<=this.maps[0].length-1?d+l-1:this.maps[0].length-1;o=this.x-this.tileWidth;s=this.y-this.tileHeight;this.showRow=h;this.showCol=l;this.dy=
this.dx=0}if(this.type==g.map.type.STAGGERED){h=Math.round((this.screenHeight+3*this.tileHeight)/(this.tileHeight/2));l=Math.round((this.screenWidth+3*this.tileWidth)/this.tileWidth);k=f+h<=this.maps.length-1?f:this.maps.length-h<0?0:this.maps.length-h;p=f+h-1<=this.maps.length-1?f+h-1:this.maps.length-1;q=d+l<=this.maps[0].length-1?d:this.maps[0].length-l<0?0:this.maps[0].length-l;r=d+l-1<=this.maps[0].length-1?d+l-1:this.maps[0].length-1;o=this.x-this.tileWidth*1.5;s=this.y-this.tileHeight*1.5;
this.showRow=h;this.showCol=l;this.dy=this.dx=0}else if(this.type==g.map.type.DIAMOND){e=e?e-1:4;i=i?i-1:4;k=f+e<=this.maps.length-1?f:this.maps.length-1-e<0?0:this.maps.length-1-e;p=f+e<=this.maps.length-1?f+e:this.maps.length-1;q=d+i<=this.maps[0].length-1?d:this.maps[0].length-1-i<0?0:this.maps[0].length-1-i;r=d+i<=this.maps[0].length-1?d+i:this.maps[0].length-1;o=this.x+parseInt((this.screenWidth-(r-q+1)*this.tileWidth)/2);s=this.y+parseInt((this.screenHeight-(p-k+1)*this.tileHeight)/2)+(p-k)*
(this.tileHeight/2);this.showRow=e+1;this.showCol=i+1;this.dx=o;this.dy=this.y+parseInt((this.screenHeight-(p-k+1)*this.tileHeight)/2)}this.currentRow=k;this.currentCol=q;this.absoluteX=o;this.absoluteY=this.y+parseInt((this.screenHeight-(p-k+1)*this.tileHeight)/2);d=k;for(i=0;d<=p;d++,i++){k=[];f=d%2==0?0:this.tileWidth/2;if(this.type==g.map.type.ANGLE_90){e=q;for(h=0;e<=r;e++,h++)k.push({id:this.maps[d][e],x:o+h*this.tileWidth,y:s+i*this.tileHeight})}else if(this.type==g.map.type.STAGGERED){e=q;
for(h=0;e<=r;e++,h++)k.push({id:this.maps[d][e],x:o+f+h*this.tileWidth,y:s+i*(this.tileHeight/2)})}else if(this.type==g.map.type.DIAMOND){e=q;for(h=0;e<=r;e++,h++)k.push({id:this.maps[d][e],x:o+h*(this.tileWidth/2),y:s-h*(this.tileHeight/2)});o+=this.tileWidth/2;s+=this.tileHeight/2}this.area.push(k)}};this.refresh(w,x,this.showRow,this.showCol);this.render=function(f){for(var d,e=this.area.length-1;e>=0;e--){d=this.area[e].length;for(var i=d-1;i>=0;i--){d=f[this.area[e][i].id];g.canvas.drawImage(d.imageid,
d.sx,d.sy,this.tileWidth,this.tileHeight,this.area[e][i].x,this.area[e][i].y,this.tileWidth,this.tileHeight);this.area[e][i].x+=this.mapSpeedX;this.area[e][i].y+=this.mapSpeedY}}this.mapSpeedY=this.mapSpeedX=0};this.moveX=function(f){this.mapSpeedX=u(this,f)};this.moveY=function(f){this.mapSpeedY=v(this,f)};this.move=function(f,d){this.moveX(f);this.moveY(d)};this.flush=function(f){n(this,f)}}}();g.map.type={ANGLE_90:0,STAGGERED:1,DIAMOND:2}})(jsGame);
