(function(k){k.jsphysics2d=function(){return{world:function(){return function(l,m,n,o,p,q){this.x=l||0;this.y=m||0;this.width=n||0;this.height=o||0;this.g=1;this.resistance=p||0.8;this.friction=q||0.95;this.items=[];this.effect=function(a){a._vy+=this.g;if(this.width>0&&this.height>0)if(a.radius<=0){if(a.y+a.height==this.y+this.height){a._vy-=this.g;a._vx*=this.friction}else if(a.y+a.height>this.y+this.height){a.y=this.y+this.height-a.height;a._vy-=this.g;a._vy*=-this.resistance;a._vx*=this.friction}else if(a.y==
this.y){a._vy+=this.g;a._vx*=this.friction}else if(a.y<this.y){a.y=this.y;a._vy+=this.g;a._vy*=-this.resistance;a._vx*=this.friction}if(a.x+a.width>this.x+this.width){a.x=this.x+this.width-a.width;a._vx*=-this.resistance;a._vy*=this.friction}else if(a.x<this.x){a.x=this.x;a._vx*=-this.resistance;a._vy*=this.friction}}else{if(a.y+a.radius==this.y+this.height){a._vy-=this.g;a._vx*=this.friction}else if(a.y+a.radius>this.y+this.height){a.y=this.y+this.height-a.radius;a._vy-=this.g;a._vy*=-this.resistance;
a._vx*=this.friction}else if(a.y-a.radius==this.y){a._vy+=this.g;a._vx*=this.friction}else if(a.y-a.radius<this.y){a.y=this.y+a.radius;a._vy+=this.g;a._vy*=-this.resistance;a._vx*=this.friction}if(a.x+a.radius>this.x+this.width){a.x=this.x+this.width-a.radius;a._vx*=-this.resistance;a._vy*=this.friction}else if(a.x-a.radius<this.x){a.x=this.x+a.radius;a._vx*=-this.resistance;a._vy*=this.friction}}a._vx=parseInt(a._vx);a._vy=parseInt(a._vy);return this};this.addItem=function(a){this.items.push(a)};
this.step=function(){var a=this.items,i=a.length,d,b;for(d=0;d<i;d++){if(a[d].collisionX)a[d].collisionX=false;else a[d].x+=parseInt(a[d]._vx);if(a[d].collisionY)a[d].collisionY=false;else a[d].y+=parseInt(a[d]._vy)}for(d=0;d<i;d++)if(!a[d].sleep){for(b=0;b<i;b++)if(d!=b)if(a[d].radius<=0){if(a[b].radius<=0&&k.commandFuns.collisionCheck(a[d].x+a[d]._vx,a[d].y+a[d]._vy,a[d].width,a[d].height,a[b].x+a[b]._vx,a[b].y+a[b]._vy-this.g,a[b].width,a[b].height)){var c=a[d];b=a[b];var f=[c.x+c.width-b.x,b.x+
b.width-c.x,c.y+c.height-b.y,b.y+b.height-c.y],e=f[0],h=0;vx1=c._vx;vy1=c._vy;vx2=b._vx;vy2=b._vy;for(var g=1;g<f.length;g++)if(f[g]<e){e=f[g];h=g}switch(h){case 0:c.x=b.x-c.width;c._vx*=-b.resistance;c._vy*=b.friction;if(!b.sleep){if(b._vx==0)b._vx+=vx1*c.resistance;else b._vx*=-c.resistance;b._vy*=c.friction}c.collisionX=true;break;case 1:c.x=b.x+b.width;c._vx*=-b.resistance;c._vy*=b.friction;if(!b.sleep){if(b._vx==0)b._vx+=vx1*c.resistance;else b._vx*=-c.resistance;b._vy*=c.friction}c.collisionX=
true;break;case 2:c.y=b.y-c.height;c._vy*=-b.resistance;c._vx*=b.friction;if(!b.sleep){b._vy*=-c.resistance;b._vx*=c.friction}c.collisionY=true;break;case 3:c.y=b.y+b.height;c._vy*=-b.resistance;c._vx*=b.friction;if(!b.sleep){b._vy*=-c.resistance;b._vx*=c.friction}c.collisionY=true}c._vx=parseInt(c._vx);c._vy=parseInt(c._vy);b._vx=parseInt(b._vx);b._vy=parseInt(b._vy);break}}else if(a[d].radius>0)if(a[b].radius>0&&k.commandFuns.circleCollisionCheck(a[d].x+a[d]._vx,a[d].y+a[d]._vy,a[d].radius,a[b].x+
a[b]._vx,a[b].y+a[b]._vy,a[b].radius)){c=a[d];b=a[b];f=parseInt(b.radius*b.radius/(c.radius*c.radius));e=parseInt((c.y-b.y)/(c.x-b.x));h=parseInt(2*(c._vx-b._vx+e*(c._vy-b._vy))/((1+e*e)*(1+f)));g=c.radius+b.radius;var j=c.x,r=c.y,s=b.x,t=b.y;j=parseInt((g-Math.abs(j-s))/g*(j-s));g=parseInt((g-Math.abs(r-t))/g*(r-t));f=f>=0?f:0;e=e>=0?e:0;h=h>=0?h:0;if(j!=0)c.x+=j;if(g!=0)c.y+=g;c._vx-=h*f*b.resistance;c._vy-=h*f*e*b.resistance;if(!b.sleep){b._vx+=h*c.resistance;b._vy+=h*e*c.resistance}break}this.effect(a[d])}}}}(),
item:function(){return function(l,m,n,o,p,q,a,i,d,b){this.x=l||0;this.y=m||0;this.width=n||20;this.height=o||20;this.type=p||0;this.speed=q||1;this.sleep=a;this.radius=i||0;this.resistance=d||0.8;this.friction=b||0.95;this._vy=this._vx=this._av=0;this.collisionY=this.collisionX=false;this.refresh=function(){this._vy=this._vx=this._av=0;return this};this.move=function(c,f){if(!this.sleep){var e=(c+5)*Math.PI/180;if(f){this._vx+=parseInt(Math.cos(e)*f);this._vy+=parseInt(Math.sin(e)*f)}else{this._vx=
parseInt(Math.cos(e)*this.speed);this._vy=parseInt(Math.sin(e)*this.speed)}}return this};this.getMassCenter=function(){return{x:this.x+parseInt(this.width/2),y:this.y+parseInt(this.height/2)}}}}()}}()})(jsGame);
