(function(m){m.touch=function(){var a={start:true,imgs:[],width:0,height:0,offset:{left:0,top:0},startPos:{x:0,y:0},releasePos:{x:0,y:0},touches:[],path:[],tracing:false,startTime:0,stopTime:0,traceable:false},s=function(b){b.preventDefault();if(!a.start)return false;var f=a.offset.left<<0,i=a.offset.top<<0,d=a.touches;if(b.touches){for(var c=b.touches,e=c.length,j=0;j<e;j++)d[j]={e:c[j],s:-1};a.startPos={x:c[0].clientX-f<<0,y:c[0].clientY-i<<0}}else{d[0]={e:b,s:-1};a.startPos={x:b.clientX-f<<0,y:b.clientY-
i<<0}}c=a.imgs;var n=c.length;e=d.length;for(var g,h=0;h<e;h++)for(j=n-1;j>=0;j--)if(c[j]&&d[h]){g=c[j];var o=(d[h].e.clientX-f<<0)-g.x<<0,r=(d[h].e.clientY-i<<0)-g.y<<0;if(Math.abs(o)<g.w/2&&Math.abs(r)<g.h/2){g.dx=o;g.dy=r;g=true}else g=false;if(g){d[h].s=j;c[j].selected=true;break}}if(a.traceable&&e==1){a.path=[];a.tracing=true;a.startTime=(new Date).getTime();a.path[0]={x:d[0].e.clientX-f<<0,y:d[0].e.clientY-i<<0}}if(a.touchStart)b.touches?a.touchStart(b.touches):a.touchStart([b]);return false},
t=function(b){b.preventDefault();if(!a.start)return false;var f=a.offset.left<<0,i=a.offset.top<<0,d=a.touches,c=d.length,e=a.imgs,j=a.width<<0,n=a.height<<0,g,h,o,r,k,p,l=0;p=null;for(var q=0;q<c;q++)if(d[q]){if(b.touches){p=b.touches.length;for(g=0;g<p;g++)if(d[q].e.identifier==b.touches[g].identifier){d[q].e=b.touches[g];break}else d[q].e=b.touches[q]}else d[0].e=b;p=d[q].e;l=d[q].s;if(l>-1&&e[l]&&e[l].dragable){g=e[l].x;h=e[l].y;o=e[l].w/2;r=e[l].h/2;k=p.clientX-f-e[l].dx;k=k>j-o?j-o:k;k=k<o?
o:k;e[l].x=k<<0;k=p.clientY-i-e[l].dy;k=k>n-r?n-r:k;k=k<r?r:k;e[l].y=k<<0;if(Math.abs(e[l].x-g)>3||Math.abs(e[l].y-h)>3)d[q].moveFlag=true}if(a.traceable&&a.tracing&&c==1){a.stopTime=(new Date).getTime();k=a.stopTime-a.startTime<<0;if(k<1E3){g=p.clientX-f<<0;h=p.clientY-i<<0;p=a.path.length;Math.abs(g-a.path[p-1].x)<3&&Math.abs(h-a.path[p-1].y)<3||(a.path[p]={x:g,y:h})}}}if(a.touchMove)b.touches?a.touchMove(b.touches):a.touchMove([b]);return false},u=function(b){b.preventDefault();if(!a.start)return false;
var f=a.offset.left<<0,i=a.offset.top<<0,d=a.imgs,c=a.touches,e=c.length;if(b.touches)for(var j=b.touches,n=j.length,g=false,h=0;h<e;h++){g=false;for(var o=0;o<n;o++)if(c[h].e.identifier==j[o].identifier){g=true;break}if(!g){a.releasePos={x:c[h].e.clientX-f<<0,y:c[h].e.clientY-i<<0};if(c[h].s>-1){d[c[h].s].selected=false;if(c[h].moveFlag)a.draged&&d[c[h].s].dragable&&a.draged(d[c[h].s]);else a.click&&d[c[h].s].clickable&&a.click(d[c[h].s])}c.splice(h,1);h--;e--}}else{if(c[0].s>-1)if(d[c[0].s]){d[c[0].s].selected=
false;if(c[0].moveFlag)a.draged&&d[c[0].s].dragable&&a.draged(d[c[0].s]);else a.click&&d[c[0].s].clickable&&a.click(d[c[0].s]);c[0].s=-1}c[0].moveFlag=false;a.releasePos={x:b.clientX-f<<0,y:b.clientY-i<<0}}if(a.traceable)a.tracing=false;if(a.touchEnd)b.touches?a.touchEnd(b.touches):a.touchEnd([b]);return false};return{imgs:a.imgs,init:function(b){a.width=m.canvas.screen.getWidth();a.height=m.canvas.screen.getHeight();a.offset.left=m.getDom("jsGameScreen").offsetLeft;a.offset.top=m.getDom("jsGameScreen").offsetTop;
a.traceable=b;this.bind()},create:function(b,f,i){var d=a.imgs,c=d.length;d[c]=b;d[c].dx=0;d[c].dy=0;d[c].clickable=f;d[c].dragable=i},click:function(b){a.click=b},draged:function(b){a.draged=b},touchStart:function(b){a.touchStart=b},touchMove:function(b){a.touchMove=b},touchEnd:function(b){a.touchEnd=b},resize:function(b){a.resize=b},bind:function(){var b=m.getDom("jsGameScreen");m.canvas.screen.getTouch()?m.events.touchStart(function(f){s(f)}).touchMove(function(f){t(f)}).touchEnd(function(f){u(f)}):
m.events.mouseDown(function(){s(event)}).mouseMove(function(){t(event)}).mouseUp(function(){u(event)});document.getElementsByTagName("body")[0].onresize=function(){a.resize&&a.resize();a.offset.left=m.getDom("jsGameScreen").offsetLeft;a.offset.top=m.getDom("jsGameScreen").offsetTop};b.onmouseout=function(){for(var f=a.imgs,i=a.touches,d=i.length,c=0;c<d;c++)if(i[c].s>-1){f[i[c].s].selected=false;i[c].s=-1}}},unbind:function(){var b=m.getDom("jsGameScreen");b.onmousedown=null;b.onmousemove=null;b.onmouseup=
null;b.ontouchstart=null;b.ontouchmove=null;b.ontouchend=null},getImgs:function(){return a.imgs},deleteImg:function(b){for(var f=a.imgs,i=f.length,d=a.touches,c=d.length,e=0;e<i;e++)if(f[e]&&f[e].id==b){for(b=0;b<c;b++)if(d[b].s>e)d[b].s--;else if(d[b].s==e)d[b].s=-1;f.splice(e,1);return true}return false},getStartPos:function(){return a.startPos},getReleasePos:function(){return a.releasePos},getPath:function(){return a.path},getGesture:function(){var b;b=a.path;var f=b.length;if(f){var i,d=0;i="null";
for(var c="swipeleft",e="swiperight",j="scrollup",n="scrolldown",g=1;g<f;g++){i=b[g].x-b[g-1].x<<0;d=b[g].y-b[g-1].y<<0;if(i>0){c="";if(Math.abs(d)>20)e=""}if(i<0){e="";if(Math.abs(d)>20)c=""}if(d>0){j="";if(Math.abs(i)>20)n=""}if(d<0){n="";if(Math.abs(i)>20)j=""}}if(Math.abs(b[0].x-b[f-1].x)>100)j=n="";if(Math.abs(b[0].y-b[f-1].y)>100)c=e="";if(Math.abs(b[0].x-b[f-1].x)<20)c=e="";if(Math.abs(b[0].y-b[f-1].y)<20)j=n="";b=c||e||j||n||"null"}else b="null";return b},start:function(){a.start=true},stop:function(){a.start=
false}}}()})(jsGame);
