jsGame.ui.panel=function(e){return function(d){d=e.objExtend({id:"",width:-1,height:-1,x:0,y:0,dx:0,dy:0,hided:false,disabled:false,hovered:false,touched:false,padding:5,vPadding:10,margin:"left",layout:true,position:"",items:[],zindex:0,shape:"rect",bgColor:"",paddingColor:"",create:true,ui:{id:"",sx:0,sy:0,width:0,height:0,dx:0,dy:0},data:null,draw:function(){},partial:false},d||{});this.id=d.id;this.width=d.width;this.height=d.height;this._ix=d.x;this._iy=d.y;this.x=this._ix;this.y=this._iy;this.dx=
d.dx;this.dy=d.dy;this._idx=this.dx;this._idy=this.dy;this.hided=d.hided;this.disabled=d.disabled;this.hovered=d.hovered;this.touched=d.touched;this.padding=d.padding;this.vPadding=d.vPadding;this.margin=d.margin;this.layout=d.layout;this.position=d.position;this.items=d.items;this.data=d.data;this.draw=d.draw;this.rendered=true;for(var h=0;h<this.items.length;h++){this.items[h]._ix=this.items[h].x;this.items[h]._iy=this.items[h].y}this.zindex=d.zindex;this.shape=d.shape;this.type="panel";this.bgColor=
d.bgColor;this.paddingColor=d.paddingColor;this.scrollPath=[];this.contextWidth=this.width-this.padding*2;this.contextHeight=0;this.ui=d.ui;this.bgImage=null;this.partial=d.partial;if(this.ui.id!="")this.bgImage=e.getImage(this.ui.id);this.refresh=function(){this.dx=this._idx;this.dy=this._idy;if(this.position=="absolute"){for(var b=0,a,c=0;c<this.items.length;c++){a=this.items[c];a.parent=this;a.x=a._ix+this.x+this.padding;a.y=a._iy+this.y+this.padding;a.refresh&&a.refresh();if(!a.hided&&a.y+a.height>
b)b=a.y+a.height-this.y}this.contextHeight=b-this.padding}else{var f=this.y+this.dy+this.padding;this.contextHeight=this.padding*2;switch(uiCoreArgs.enums.floatType[this.margin]){case uiCoreArgs.enums.floatType.left:b=this.x+this.dx+this.padding;for(c=0;c<this.items.length;c++){a=this.items[c];if(!a.hided){a.parent=this;a.x=b;a.y=f;a.refresh&&a.refresh();a.zindex=this.zindex;b+=a.width;this.contextWidth+=a.width;if(this.layout)if(c<this.items.length-1&&b+this.items[c+1].width>this.x+this.width-this.padding){b=
this.x+this.dx+this.padding;f+=a.height+this.vPadding;this.contextWidth=this.width-this.padding*2;this.contextHeight+=a.height+this.vPadding}else if(c==this.items.length-1)this.contextHeight+=a.height}}break;case uiCoreArgs.enums.floatType.right:b=this.x+this.dx+this.width;for(c=0;c<this.items.length;c++){a=this.items[c];if(!a.hided){a.parent=this;b-=a.width+this.padding;a.x=b;a.y=f;a.refresh&&a.refresh();a.zindex=this.zindex;this.contextWidth+=a.width;if(this.layout)if(c<this.items.length-1&&b-this.items[c+
1].width-this.padding<this.x+this.padding){b=this.x+this.dx+this.width;f+=a.height+this.vPadding;this.contextWidth=this.width-this.padding*2;this.contextHeight+=a.height+this.vPadding}else if(c==this.items.length-1)this.contextHeight+=a.height}}break;case uiCoreArgs.enums.floatType.center:for(c=a=0;c<this.items.length;c++)this.items[c].hided||(a+=this.items[c].width);a+=(this.items.length-1)*this.padding;b=this.x+this.dx+parseInt((this.width-a)/2);this.contextWidth=a;for(c=0;c<this.items.length;c++){a=
this.items[c];if(!a.hided){a.parent=this;a.x=b;a.y=f;a.refresh&&a.refresh();a.zindex=this.zindex;b+=a.width+this.padding}}}}};this.show=function(){e.ui.core.show(this)};this.hide=function(){e.ui.core.hide(this)};this.renderItems=function(){e.ui.core.renderItems(this)};this.disposed=function(){e.ui.core.disposed(this)};this.render=function(){e.ui.core.render(this)};this.addChild=function(b){b.parent=this;this.items.push(b);e.events.addChild(b)};this.clearChild=function(){for(var b=this.items.length-
1;b>=0;b--)e.events.removeChild(this.items[b]);this.items=[]};this.__render__=function(b){if(b!=uiCoreArgs.enums.renderType.hide){b=e.ui.context;if(this.bgImage){var a=this.ui;b.drawImage(this.bgImage,a.sx,a.sy,a.width,a.height,this.x+a.dx,this.y+a.dy,a.width,a.height)}else if(this.bgColor!=""){b.fillStyle=this.bgColor;b.fillRect(this.x,this.y,this.width,this.height)}else if(this.paddingColor!=""){b.fillStyle=this.paddingColor;b.fillRect(this.x+this.padding,this.y+this.padding,this.width-(this.padding<<
1),this.height-(this.padding<<1))}this.draw(b,this);b.save();b.beginPath();b.rect(this.x+this.padding,this.y+this.padding,this.width-(this.padding<<1),this.height-(this.padding<<1));b.closePath();b.clip();if(this.scrollPath.length>0){a=this.scrollPath.shift();var c=this.items,f=c.length,g;this.dx+=a.dx;this.dy+=a.dy;for(var j=0;j<f;j++){g=c[j];g.y+=a.dy;g.refresh&&g.refresh()}}this.renderItems();if(this.items.length>0&&this.contextHeight>this.height){a=this.width-this.padding*2;c=this.height-this.padding*
2;f=this.items[0];var i;for(g=this.items.length-1;g>=0;g--)if(!this.items[g].hided){i=this.items[g];break}if(f.y>this.y+this.padding)this.scrollPath=[{dx:0,dy:this.y+this.padding-f.y}];else if(i&&i.y<this.y+this.height-this.padding-i.height)this.scrollPath=[{dx:0,dy:this.y+this.height-this.padding-i.height-i.y}];b.fillStyle="#999999";b.fillRect(parseInt(-this.dx*(a/this.contextWidth)+this.x+this.width-this.padding-3),parseInt(-this.dy*(c/this.contextHeight)+this.y+this.padding),3,parseInt(c/this.contextHeight*
c))}b.restore()}};this.__disposed__=function(){for(var b,a=this.items.length-1;a>=0;a--){b=this.items[a];e.events.unbind(b,"touchStart");e.events.unbind(b,"touchMove");e.events.unbind(b,"touchEnd")}};if(d.create){this.refresh();e.events.addChild(this);this.render()}d=null}}(jsGame);
